### ISSUE TITLE
sunlight

### ISSUE THREAD

**Issue by REDKING-11** [RayzsYT/ControlPlayer#4]
My POV doesn't change for my chosen player, and it doesn't work. It says I'm controlling the player, but nothing happens, and all this happened after I installed Sunlight and Vulcan anti-cheat

**Comment by REDKING-11** [comment]
Only shifting works, I found out, but you are not in the body still

**Comment by RayzsYT** [comment]
I tried to recreate this bug as you stated with the two following plugins on my spigot 1.20.1 server.

Sunlight: https://www.spigotmc.org/resources/sunlight-best-essentials-cmi-alternative.67733/
and Vulcan: https://www.spigotmc.org/resources/vulcan-anti-cheat-advanced-cheat-detection-1-7-1-20-4.83626/

And it seems to work on my server just fine. Are there any console errors or are you using a server-jar I'm not aware of that might cause this error?

Here's the video of the test:
https://www.youtube.com/watch?v=Dx2vJX8TOvA
---------------------
I'm afraid that this is all I can do for you so far. I can only tell you what might cause this error:
My plugins works by teleporting the player each time and it seems that another plugin on your server might cancel that teleportation-process which leads to that bug. It can also be caused by your server-jar for some kind of "performance-regulation". But i can not tell for certain. 

Please let me know if you have any further information about this bug.

**Comment by REDKING-11** [comment]
![image_2024-03-21_161918928](https://github.com/RayzsYT/ControlPlayer/assets/99126547/762e2bb8-68fd-43db-b523-bc7abaa53b63)
well these are all the plugins I use

**Comment by RayzsYT** [comment]
Why using GrimAC and Vulcan at the same time? Both of AntiCheats.

Btw what Server-Jar/Spigot are u using and please tell me since what plugin exactly you have installed, CP isn't working anymore. Is it since you've installed Vulcan, or Sunlight?

**Comment by REDKING-11** [comment]
about that time

**Comment by REDKING-11** [comment]
![image](https://github.com/RayzsYT/ControlPlayer/assets/99126547/2879f8d5-e094-4930-a95f-fd12a24bde3e)

**Comment by REDKING-11** [comment]
![image](https://github.com/RayzsYT/ControlPlayer/assets/99126547/b9e9809f-39a0-406e-aa3a-d79f8a345418)

**Comment by REDKING-11** [comment]
I heard that Grimac and Vulcan are a good combo. That's why I'm using them

**Comment by RayzsYT** [comment]
Are there any console errors?

**Comment by REDKING-11** [comment]
let me check real quick

**Comment by REDKING-11** [comment]
Umm, it's working for me, but when I tried using it on another player, it didn't work.
I used my alt

**Comment by RayzsYT** [comment]
Can you make a video how it looks like and send it to me?

**Comment by REDKING-11** [comment]
I can't. I don't have any online rn

**Comment by REDKING-11** [comment]
Now it started working on the players, too???
Fantastic plugin, btw :D

**Comment by RayzsYT** [comment]
Weird that it is working now but atleast it does ^^

Would you say this issue is solved?

**Comment by REDKING-11** [comment]
For now, it is
thank you for your quick help :D

**Comment by RayzsYT** [comment]
If that's the case. ^^
Feel free to open a new ticket if the same problem happens more frequently than before. That way it's easier to find out what causes it.

If you like, it would help me alot if you could share your experience with my plugin by leaving a review on the spigot ressource page of ControlPlayer. ^^

**Comment by REDKING-11** [comment]
sure thing

**Comment by RayzsYT** [comment]
Much appreciated ^^
